In [140]:
import numpy as np
import pandas as pd

In [141]:
movies = pd.read_csv('/content/Movies Dataset.csv')
movies.head(2)

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
0,1,Fast X,Action-Crime-Thriller,en,Over many missions and against impossible odds...,6682.100,Universal Pictures-Original Film-One Race-Perf...,5/17/2023,340000000,686700000,142.0,Released,The end of the road begins.,7.331,1856,Vin Diesel-Michelle Rodriguez-Tyrese Gibson-Lu...,sequel-revenge-racing-family-cars,/fiVW06jE7z9YnO4trhaMEdclSiC.jpg,/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg,19603-445954-697843-603692-781009-502356-74735...
1,2,The Pope's Exorcist,Horror-Mystery-Thriller,en,Father Gabriele Amorth Chief Exorcist of the V...,5953.227,Screen Gems-2.0 Entertainment-Jesus & Mary-Wor...,4/5/2023,18000000,65675816,103.0,Released,Inspired by the actual files of Father Gabriel...,7.433,545,Russell Crowe-Daniel Zovatto-Alex Essoe-Franco...,spain-rome italy-vatican-pope-pig-possession-c...,/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg,/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg,713704-296271-502356-1076605-1084225-1008005-9...

In [142]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    99999 non-null  int64
 1   title                 99999 non-null  object
 2   genres                96002 non-null  object
 3   original_language     99999 non-null  object
 4   overview              97278 non-null  object
 5   popularity            99999 non-null  float64
 6   production_companies  80327 non-null  object
 7   release_date          99526 non-null  object
 8   budget                99999 non-null  int64
 9   revenue               99999 non-null  int64
 10  runtime               99494 non-null  float64
 11  status                99999 non-null  object
 12  tagline               41274 non-null  object
 13  vote_average          99999 non-null  float64
 14  vote_count            99999 non-null  int64
 15  credits               95762 non-null  object
 16  keywords              62991 non-null  object
 17  poster_path           97760 non-null  object
 18  backdrop_path         80062 non-null  object
 19  recommendations       30985 non-null  object
dtypes: float64(3), int64(4), object(13)
memory usage: 15.3+ MB

In [143]:
movies.drop(columns=["production_companies"	,"overview" , "tagline" , "credits" , "keywords" , "poster_path" , "backdrop_path" , "recommendations"] ,axis =1 , inplace = True )

In [144]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 99999 non-null  int64
 1   title              99999 non-null  object
 2   genres             96002 non-null  object
 3   original_language  99999 non-null  object
 4   popularity         99999 non-null  float64
 5   release_date       99526 non-null  object
 6   budget             99999 non-null  int64
 7   revenue            99999 non-null  int64
 8   runtime            99494 non-null  float64
 9   status             99999 non-null  object
 10  vote_average       99999 non-null  float64
 11  vote_count         99999 non-null  int64
dtypes: float64(3), int64(4), object(5)
memory usage: 9.2+ MB

In [145]:
movies.isna().sum()

id                      0
title                   0
genres               3997
original_language       0
popularity              0
release_date          473
budget                  0
revenue                 0
runtime               505
status                  0
vote_average            0
vote_count              0
dtype: int64

In [146]:
movies.dropna(inplace=True)

In [147]:
movies.isna().sum()

id                   0
title                0
genres               0
original_language    0
popularity           0
release_date         0
budget               0
revenue              0
runtime              0
status               0
vote_average         0
vote_count           0
dtype: int64

In [148]:
movies.duplicated().sum()

0

In [149]:
movies.drop_duplicates(inplace=True)

In [150]:
movies["release_date"] = pd.to_datetime(movies['release_date'], format="%d/%m/%Y", errors='coerce')

In [151]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95396 entries, 0 to 99998
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 95396 non-null  int64
 1   title              95396 non-null  object
 2   genres             95396 non-null  object
 3   original_language  95396 non-null  object
 4   popularity         95396 non-null  float64
 5   release_date       40744 non-null  datetime64[ns]
 6   budget             95396 non-null  int64
 7   revenue            95396 non-null  int64
 8   runtime            95396 non-null  float64
 9   status             95396 non-null  object
 10  vote_average       95396 non-null  float64
 11  vote_count         95396 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 9.5+ MB

In [152]:
movies.duplicated().sum()

0

In [153]:
movies["genres"].value_counts()

genres
Drama                                  9245
Documentary                            7598
Comedy                                 7388
Horror                                 2895
Drama-Romance                          2491
                                       ...
Music-TV Movie-Romance                    1
Romance-Comedy-Music-Action-Fantasy       1
Comedy-Romance-TV Movie-Drama             1
Animation-Comedy-Fantasy-Family           1
Fantasy-Animation-Adventure-Drama         1
Name: count, Length: 6735, dtype: int64

In [154]:
def extract_first_genre(genres_str):

    if pd.isna(genres_str) or genres_str == '':
        return None
    elif '-' in genres_str:
        return genres_str.split('-')[0]
    else:
        return genres_str

movies['genres'] = movies['genres'].apply(extract_first_genre)

In [155]:
movies["genres"].value_counts()

genres
Drama              22193
Comedy             17375
Documentary         9751
Action              8770
Horror              7217
Thriller            4687
Animation           4294
Romance             3566
Crime               3311
Adventure           2423
Music               2151
Family              1932
Science Fiction     1774
TV Movie            1529
Fantasy             1212
Mystery             1106
Western              862
War                  677
History              566
Name: count, dtype: int64

In [156]:
movies["title"].value_counts()

title
A Christmas Carol                         20
Cinderella                                16
Alone                                     14
Swingers                                  12
Beauty and the Beast                      12
                                          ..
The Story of My Wife                       1
Another Woman's Life                       1
Jesus Christ Superstar Live in Concert     1
Sauna                                      1
Horrors of War                             1
Name: count, Length: 79432, dtype: int64

In [157]:
movies.drop_duplicates(subset=['title'], inplace=True)
movies["title"].value_counts()

title
Fast X                        1
Going Bye-Bye!                1
Curse III: Blood Sacrifice    1
Trapped Daughter              1
Workhorse Queen               1
                             ..
Goliath                       1
Last Winter, We Parted        1
The Rebels of PT-218          1
A/R Andata + Ritorno          1
Horrors of War                1
Name: count, Length: 79432, dtype: int64

In [158]:
index_to_drop = movies[movies['runtime'] == 0].index
movies.drop(index_to_drop, inplace=True)

In [159]:
movies.dropna(subset=['release_date'], inplace=True)

In [160]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32639 entries, 1 to 99992
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 32639 non-null  int64
 1   title              32639 non-null  object
 2   genres             32639 non-null  object
 3   original_language  32639 non-null  object
 4   popularity         32639 non-null  float64
 5   release_date       32639 non-null  datetime64[ns]
 6   budget             32639 non-null  int64
 7   revenue            32639 non-null  int64
 8   runtime            32639 non-null  float64
 9   status             32639 non-null  object
 10  vote_average       32639 non-null  float64
 11  vote_count         32639 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 3.2+ MB

In [161]:
movies.describe()

,id,popularity,release_date,budget,revenue,runtime,vote_average,vote_count
count,32639.000000,32639.000000,32639,3.263900e+04,3.263900e+04,32639.000000,32639.000000,32639.000000
mean,47703.532155,9.070074,2002-02-20 15:02:43.129997952,2.929759e+06,7.295754e+06,96.172677,5.720799,212.355280
min,2.000000,1.952000,1900-01-01 00:00:00,0.000000e+00,0.000000e+00,1.000000,0.000000,0.000000
25%,22668.500000,2.642000,1993-07-11 00:00:00,0.000000e+00,0.000000e+00,84.000000,5.149500,6.000000
50%,46479.000000,3.948000,2009-11-06 00:00:00,0.000000e+00,0.000000e+00,93.000000,6.100000,20.000000
75%,71985.500000,7.556000,2017-07-07 00:00:00,0.000000e+00,0.000000e+00,105.000000,6.800000,64.000000
max,99993.000000,5953.227000,2025-02-02 00:00:00,5.000000e+08,1.671537e+09,51420.000000,10.000000,30708.000000
std,28767.072590,60.186885,NaN,1.461497e+07,4.950096e+07,285.993447,1.870225,1009.787552

In [162]:
movies.describe(include = 'object')

                      title genres original_language    status
count                 32639  32639             32639     32639
unique                32639     19                81         3
top     The Pope's Exorcist  Drama                en  Released
freq                      1   7466             21297     32628

In [163]:
#the average runtime of all movies
average_runtime = np.mean(movies['runtime']).round(0)
print(f"Average runtime: {average_runtime} minutes")

Average runtime: 96.0 minutes

In [164]:
#the highest budget for a movie
highest_budget = movies['budget'].max()
highest_budget

500000000

In [165]:
 #movies were released in each year(top 10 years)
movies['release_year'] = movies['release_date'].dt.year
yearly_counts = movies.groupby('release_year')['title'].count().sort_values(ascending=False).head(10)
yearly_counts

release_year
2019    1614
2018    1517
2021    1504
2017    1451
2020    1406
2016    1366
2022    1213
2015    1161
2014    1085
2013    1022
Name: title, dtype: int64

In [166]:
#the total revenue generated by all movies
total_revenue = movies['revenue'].sum()
total_revenue

238126116836

In [167]:
#the median popularity score of movies
median_popularity = movies['popularity'].median()
median_popularity

3.948

In [168]:
#the most frequent genre of movies
genre_counts = movies['genres'].value_counts()
genre_counts

genres
Drama              7466
Comedy             6076
Documentary        3121
Action             3081
Horror             2466
Thriller           1535
Animation          1517
Romance            1264
Crime              1161
Adventure           861
Family              703
Science Fiction     657
Music               600
TV Movie            549
Fantasy             405
Mystery             372
Western             337
War                 258
History             210
Name: count, dtype: int64

In [169]:
#the average vote average of all movies
average_vote_average = np.mean(movies['vote_average'])
average_vote_average

5.720799442384878

In [170]:
#the release year of the oldest movie
oldest_movie_year = movies['release_date'].min()
oldest_movie_year.date()

datetime.date(1900, 1, 1)

In [171]:
#numbers of movies have a vote average greater than 8
high_vote_average_count = movies[movies['vote_average'] > 8]['vote_average'].count()
high_vote_average_count

1078

In [172]:
#the title of the movie with the longest runtime
longest_runtime_movie = movies.loc[movies['runtime'].idxmax(), 'title']
longest_runtime_movie

'Logistics'

In [173]:
#the title of the movie with the smallest runtime
smallest_runtime_movie = movies.loc[movies['runtime'].idxmin(), 'title']
smallest_runtime_movie

'The strange world of Gumball'

In [174]:
# the average runtime of movies grouped by genre
average_runtime_by_genre = movies.groupby('genres')['runtime'].mean().sort_values(ascending=False).round(2)
average_runtime_by_genre

genres
History            113.68
War                108.42
Music              106.34
Action             104.87
Drama              102.75
Documentary        102.07
Crime              100.84
Romance             97.56
Adventure           97.19
Thriller            96.76
Mystery             94.66
Fantasy             94.26
Western             92.91
Comedy              92.85
TV Movie            90.41
Science Fiction     88.79
Horror              88.72
Family              87.35
Animation           55.96
Name: runtime, dtype: float64

In [175]:
#the top 10 highest-grossing movies (revenue - budget)
movies['profit'] = movies['revenue'] - movies['budget']
top_5_highest_grossing = movies[['title', 'profit']].sort_values('profit', ascending=False).head(10)
top_5_highest_grossing

                                              title      profit
464                                  Jurassic World  1521537444
367                                       Furious 7  1325341399
184    Harry Potter and the Deathly Hallows: Part 2  1216511219
4                       The Super Mario Bros. Movie  1178766975
670   The Lord of the Rings: The Return of the King  1024888979
580                                           Joker  1019458282
610                                         Aquaman   988528393
418                         The Fate of the Furious   986005118
1085                                 Captain Marvel   979416446
415                                        Zootopia   873784195

In [188]:
#genre has the highest sum popularity score
genre_popularity = movies.groupby('genres')['popularity'].sum().sort_values(ascending=False).head(10).round(2)
genre_popularity

genres
Drama          56339.73
Comedy         43573.54
Action         39728.54
Horror         34622.66
Animation      24236.00
Thriller       14845.72
Documentary    13346.56
Romance        12040.09
Adventure      10450.94
Crime          10378.99
Name: popularity, dtype: float64

In [177]:
#genre has the highest sum vote count
genre_vote_count = movies.groupby('genres')['vote_count'].sum().sort_values(ascending=False)
genre_vote_count

genres
Drama              1308126
Action             1240029
Comedy             1098021
Adventure           564996
Horror              465478
Animation           357825
Crime               336705
Thriller            330134
Science Fiction     307331
Fantasy             274753
Romance             189193
Family              135494
Mystery              95614
Documentary          81519
War                  40006
Western              37281
Music                28854
History              24911
TV Movie             14794
Name: vote_count, dtype: int64

In [178]:
#language has the highest popularity score for movies
language_popularity = movies.groupby('original_language')['popularity'].sum().sort_values(ascending=False)
language_popularity

original_language
en    208354.806
ja     16438.958
es     14248.018
fr     11868.650
ko      7730.656
         ...
dz         2.642
st         2.601
se         2.436
az         2.174
or         2.026
Name: popularity, Length: 81, dtype: float64

In [179]:
#the total revenue generated by movies in each genre
total_revenue_by_genre = movies.groupby('genres')['revenue'].sum().sort_values(ascending=False)
total_revenue_by_genre

genres
Action             58038546233
Comedy             37551646964
Drama              32159914974
Adventure          25891877046
Animation          18047307067
Fantasy            12966617312
Horror             10486890643
Science Fiction    10009852894
Crime               8411574600
Thriller            8350670046
Family              5696928164
Romance             4420325558
Mystery             1935480533
War                 1277812177
Music                948432462
Western              708233649
History              591055384
Documentary          577223130
TV Movie              55728000
Name: revenue, dtype: int64

In [180]:
#top 10 movies with the highest budget
top_10_budget_movies = movies.sort_values('budget', ascending=False).head(10)[['title', "budget"]]
top_10_budget_movies

                                               title     budget
97533                                           DeAD  500000000
317    Mission: Impossible - Dead Reckoning Part One  290000000
745                                     Spider-Man 3  258000000
546        The Hobbit: The Battle of the Five Armies  250000000
917              The Hobbit: The Desolation of Smaug  250000000
247     Harry Potter and the Deathly Hallows: Part 1  250000000
183           Harry Potter and the Half-Blood Prince  250000000
868                                      John Carter  250000000
418                          The Fate of the Furious  250000000
26                    Guardians of the Galaxy Vol. 3  250000000

In [189]:
#the average budget for movies released in each year
avg_budget_by_year = movies.groupby('release_year')[['budget']].mean().sort_values('budget', ascending=False).head(10)
avg_budget_by_year

                    budget
release_year
2023          6.997594e+06
1997          6.723333e+06
1998          6.138050e+06
2001          5.976343e+06
2000          5.480705e+06
2002          5.368375e+06
1996          5.287380e+06
2004          5.240576e+06
2007          5.201597e+06
2005          5.187259e+06

In [182]:
#the movies with a vote average greater than 8 and a budget over $100 million
movies_high_rated_high_budget = movies[(movies['vote_average'] > 8) & (movies['budget'] > 100000000)][['title' , 'revenue']]
movies_high_rated_high_budget

                                             title     revenue
26                  Guardians of the Galaxy Vol. 3   821801000
184   Harry Potter and the Deathly Hallows: Part 2  1341511219
283                                   Interstellar   701729206
783                     Terminator 2: Judgment Day   520000000
1168                                     Gladiator   465361176

In [191]:
#the average budget and revenue for movies in each original language
sum_budget_by_language = movies.groupby('original_language')[['budget']].mean().sort_values("budget",ascending=False).head(5)
sum_budget_by_language

                         budget
original_language
se                 4.450000e+06
en                 4.095738e+06
zh                 2.727207e+06
kk                 2.166667e+06
ca                 2.106667e+06

In [192]:
#the total profit each year (revenue - budget)
total_profit_each_year = movies.groupby('release_year')[['profit']].sum().sort_values('profit', ascending=False).head(10)
total_profit_each_year

                  profit
release_year
2017          7607809389
2018          6907990896
2015          6547823980
2011          6421240957
2016          6416248580
2019          6118030801
2022          6021627345
2013          5991482874
2014          5953195217
2010          5619198887

In [193]:
#the total profit each genre (revenue - budget)
total_profit_each_genre = movies.groupby('genres')[['profit']].sum().sort_values('profit', ascending=False).head(10)
total_profit_each_genre

                      profit
genres
Action           35382262957
Comedy           22398719637
Drama            17774665256
Adventure        16053172609
Animation        12478343903
Fantasy           9054162552
Horror            6903717428
Science Fiction   5708318935
Crime             4382649285
Thriller          4338495270

In [187]:
movies.to_csv('movies_updated.csv', index=False)